### ISSUE TITLE
Hello -- hope  you don't mind me commenting on your code!

### ISSUE THREAD

**Issue by jasperlieber** [ash42/adventofcode#1]
https://github.com/ash42/adventofcode/blob/fc475dfaea893c652a1d9aec0d765150bc5dcb5a/adventofcode2023/src/nl/michielgraat/adventofcode2023/day17/Element.java#L90

**Comment by jasperlieber** [comment]
(I didn't really mean to create an "issue" with  your code -- I only wanted to comment, but didn't see how to do that!!!)

Glad to see your solution to AOC23-17.  I was stuck with some awful off-by-one issue in my code, and your code helped me figure out my bug.  One small comment -- the compareTo() function need only compare the heatloss value -- the other values aren't necessary.  (I mention this because I thought that might have been an issue I was having.)

**Comment by ash42** [comment]
Thanks for your comment, and I am glad the code helped you. Nice catch by the way! If I remember correctly I wrote the compareTo early on and never bothered to look at it again once the code worked.
